# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration files
# file_template = %%(rev)s_%%(slug)s

# sys.path pathprefix to prepend to sys.path before loading url
# prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# timezone =

# max length of characters to clone to slug when generating new file names
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow modules to be loaded relative to the
# directory containing the alembic.ini file
# sourceless = false

# version location specification; This defaults
# to alembic/versions.  When using multiple version
# directories, paths must be separated by ',' or whitespace
# version_locations = %(here)s/bar:%(here)s/bat:alembic/versions

# version path separator; as of Alembic 1.11, this defaults to 'os'
# which uses os.pathsep.  other options include 'space', 'newline',
# or ','
# version_path_separator = :
version_path_separator = os  # Use os.pathsep. Default since 1.11

# set to 'true' to search for scripts in subdirectories
# recursive_version_locations = false

# La URL real se carga dinámicamente en env.py desde settings (DATABASE_URL). Este es solo un placeholder.
sqlalchemy.url = postgresql+asyncpg://user:password@database:5432/meraki_db

[post_write_hooks]
# post_write_hooks defines scripts or Python functions that are run
# on newly generated revision scripts.  See the documentation for details.

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = INFO
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stdout,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(asctime)s %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
